---
# The container image and tag to use
imageUri: registry.access.redhat.com/ubi9/httpd-24:latest

# The hostname of the Ingress
ingressHost: sample-app.example.com

# The size of the /var/www volume
wwwPvcSize: 3Gi

# The size of the /var/log/httpd volume
logPvcSize: 3Gi
...